# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('data', models.CharField(max_length=200)),
            ],
        ),
    ]
